name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    name: Build and test with GCC
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc g++ catch2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure

  build-clang:
    runs-on: ubuntu-latest
    name: Build and test with Clang
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang g++ catch2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure
  
  coverage-gcc:
    runs-on: ubuntu-latest
    name: Coverage (GCC/gcov)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc g++ catch2 gcovr
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure
      - name: Run gcovr (coverage)
        run: |
          cd build
          gcovr --root .. --xml -o coverage.xml
          gcovr --root .. --html --html-details -o coverage.html
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcc-coverage-report
          path: build/coverage.*