name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gcc-debug:
    runs-on: ubuntu-latest
    name: Build and test with GCC (Debug)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc g++ catch2 gcovr
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure
      - name: Run gcovr (coverage)
        run: |
          cd build
          gcovr --root .. --filter ../src --xml -o coverage.xml
          gcovr --root .. --filter ../src --html --html-details -o coverage.html
      - name: Commit and push code coverage report
        env: 
          CC_COMMIT_MESSAGE: Code coverage artifacts
          CC_COMMIT_AUTHOR: Code Coverage Action
        run: |
          git config --global user.name "${{ env.CC_COMMIT_AUTHOR }}"
          git config --global user.email "o_d_lomax@users.noreply.github.com"
          git add docs
          git commit -m "${{ env.CC_COMMIT_MESSAGE }}"
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push

  build-gcc-release:
    runs-on: ubuntu-latest
    name: Build and test with GCC (Release)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc g++ catch2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure


  build-clang-debug:
    runs-on: ubuntu-latest
    name: Build and test with Clang (Debug)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang g++ catch2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure

  build-clang-release:
    runs-on: ubuntu-latest
    name: Build and test with Clang (Release)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang g++ catch2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure