name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-gcc-debug:
    runs-on: ubuntu-latest
    name: Build and test with GCC (Debug)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc g++ catch2 gcovr
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure
      - name: Run gcovr (coverage)
        run: |
          cd build
          gcovr --root .. --filter ../src --xml -o coverage.xml
          gcovr --root .. --filter ../src --html --html-details -o coverage.html
      - name: Push coverage report
        run: |
          cp build/coverage.*html coverage/ |
          git add coverage/coverage.*html
          git commit -m "Add coverage report"
          git push

  build-gcc-release:
    runs-on: ubuntu-latest
    name: Build and test with GCC (Release)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc g++ catch2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure


  build-clang-debug:
    runs-on: ubuntu-latest
    name: Build and test with Clang (Debug)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang g++ catch2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure

  build-clang-release:
    runs-on: ubuntu-latest
    name: Build and test with Clang (Release)
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang g++ catch2
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest --output-on-failure